'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AGIFormu
    
    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager
    
    '''<summary>
    '''Mesaj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Mesaj As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Kaydet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kaydet As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Yazdir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Yazdir As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Temizle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Temizle As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''LKaydet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LKaydet As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LYazdir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LYazdir As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LTemizle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTemizle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''InputDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InputDoc As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pSicilNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pSicilNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pCepNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pCepNo As Global.Telerik.Web.UI.RadMaskedTextBox
    
    '''<summary>
    '''pAdSoyad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pAdSoyad As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pIl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pIl As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pBolum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pBolum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pIlce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pIlce As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pMasrafYeri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pMasrafYeri As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pAdres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pAdres As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lAskerlik control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lAskerlik As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pAskerlik control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pAskerlik As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Cinsiyet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cinsiyet As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''CalAltGrup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalAltGrup As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lTerhisTar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTerhisTar As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pTerhisTar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pTerhisTar As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pTecil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pTecil As Global.Telerik.Web.UI.RadMonthYearPicker
    
    '''<summary>
    '''pMedeniHal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pMedeniHal As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''EsInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EsInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''EsBoschDurum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EsBoschDurum As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lEsSicilNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lEsSicilNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''EsSicilNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EsSicilNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''bEsYenile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bEsYenile As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''EsAdSoyad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EsAdSoyad As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''EsIsDurum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EsIsDurum As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''EsAGIDurum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EsAGIDurum As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CocukInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CocukInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbl0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl0 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CAdSoyad0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAdSoyad0 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CDogumTar0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CDogumTar0 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''CCinsiyet0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CCinsiyet0 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Cogrenim0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cogrenim0 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CAdSoyad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAdSoyad1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CDogumTar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CDogumTar1 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''CCinsiyet1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CCinsiyet1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Cogrenim1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cogrenim1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CAdSoyad2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAdSoyad2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CDogumTar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CDogumTar2 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''CCinsiyet2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CCinsiyet2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Cogrenim2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cogrenim2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbl3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CAdSoyad3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAdSoyad3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CDogumTar3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CDogumTar3 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''CCinsiyet3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CCinsiyet3 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Cogrenim3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cogrenim3 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbl4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CAdSoyad4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAdSoyad4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CDogumTar4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CDogumTar4 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''CCinsiyet4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CCinsiyet4 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Cogrenim4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cogrenim4 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbl5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CAdSoyad5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAdSoyad5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CDogumTar5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CDogumTar5 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''CCinsiyet5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CCinsiyet5 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Cogrenim5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cogrenim5 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbl6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CAdSoyad6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAdSoyad6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CDogumTar6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CDogumTar6 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''CCinsiyet6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CCinsiyet6 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''COgrenim6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COgrenim6 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbl7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CAdSoyad7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAdSoyad7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CDogumTar7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CDogumTar7 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''CCinsiyet7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CCinsiyet7 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Cogrenim7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cogrenim7 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbl8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl8 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CAdSoyad8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAdSoyad8 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CDogumTar8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CDogumTar8 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''CCinsiyet8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CCinsiyet8 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Cogrenim8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cogrenim8 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbl9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl9 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CAdSoyad9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAdSoyad9 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CDogumTar9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CDogumTar9 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''CCinsiyet9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CCinsiyet9 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Cogrenim9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cogrenim9 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''PrintDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrintDoc As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''RadBarcode1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBarcode1 As Global.Telerik.Web.UI.RadBarcode
    
    '''<summary>
    '''ySicilNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ySicilNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCepTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCepTel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yAdSoyad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yAdSoyad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yIl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yIl As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yBolum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yBolum As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yIlce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yIlce As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yMasrafYeri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yMasrafYeri As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yAdres2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yAdres2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ylAskerlik control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ylAskerlik As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yAskerlik control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yAskerlik As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ylTerhisTar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ylTerhisTar As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yTerhisTar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yTerhisTar As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yMedeniHal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yMedeniHal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yEsInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yEsInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''yEsBoschDurum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yEsBoschDurum As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ylEsSicilno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ylEsSicilno As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yEsSicilNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yEsSicilNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yEsAdSoyad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yEsAdSoyad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yEsIsDurum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yEsIsDurum As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yEsAGIDurum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yEsAGIDurum As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CocukInfo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CocukInfo2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''yNo0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yNo0 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCAdSoyad0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCAdSoyad0 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCDogumTar0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCDogumTar0 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCCinsiyet0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCCinsiyet0 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCOgrenim0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCOgrenim0 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yNo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yNo1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCAdSoyad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCAdSoyad1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCDogumTar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCDogumTar1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCCinsiyet1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCCinsiyet1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCOgrenim1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCOgrenim1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yNo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yNo2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCAdSoyad2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCAdSoyad2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCDogumTar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCDogumTar2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCCinsiyet2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCCinsiyet2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCOgrenim2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCOgrenim2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yNo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yNo3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCAdSoyad3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCAdSoyad3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCDogumTar3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCDogumTar3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCCinsiyet3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCCinsiyet3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCOgrenim3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCOgrenim3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yNo4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yNo4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCAdSoyad4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCAdSoyad4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCDogumTar4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCDogumTar4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCCinsiyet4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCCinsiyet4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCOgrenim4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCOgrenim4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yNo5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yNo5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCAdSoyad5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCAdSoyad5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCDogumTar5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCDogumTar5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCCinsiyet5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCCinsiyet5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCOgrenim5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCOgrenim5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yNo6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yNo6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCAdSoyad6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCAdSoyad6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCDogumTar6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCDogumTar6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCCinsiyet6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCCinsiyet6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCOgrenim6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCOgrenim6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yNo7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yNo7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCAdSoyad7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCAdSoyad7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCDogumTar7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCDogumTar7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCCinsiyet7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCCinsiyet7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCOgrenim7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCOgrenim7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yNo8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yNo8 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCAdSoyad8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCAdSoyad8 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCDogumTar8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCDogumTar8 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCCinsiyet8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCCinsiyet8 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCOgrenim8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCOgrenim8 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yNo9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yNo9 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCAdSoyad9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCAdSoyad9 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCDogumTar9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCDogumTar9 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCCinsiyet9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCCinsiyet9 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yCOgrenim9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yCOgrenim9 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''IAdSoyad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAdSoyad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ITarih control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ITarih As Global.System.Web.UI.WebControls.Label
End Class
