'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FYetkiOnay

    '''<summary>
    '''RadScripTBoschOnay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScripTBoschOnay As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''BBaslik control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BBaslik As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RadGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid1 As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''BEkle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BEkle As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''BDegistir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BDegistir As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''BSil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BSil As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''Kayit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kayit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BKaydet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BKaydet As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''BVazgec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BVazgec As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''RadLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel2 As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''YtkNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YtkNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RadLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel1 As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''Aciklama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Aciklama As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RadGrid2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid2 As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''Mesaj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Mesaj As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HiddenField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenField1 As Global.System.Web.UI.WebControls.HiddenField
End Class
